name: VillagePro
version: 1.0
main: cn.popcraft.villagepro.VillagePro
api-version: 1.19
depend: [Vault]
commands:
  village:
    description: 村庄系统主命令
    aliases: [v]
    usage: /village
  recruit:
    description: 招募一个村民
    usage: /recruit
  upgrade:
    description: 打开村民升级界面
    usage: /upgrade
  crop:
    description: 管理村民收集的作物
    usage: /crop [list|withdraw <作物类型> <数量>]
  villager:
    description: 村民管理综合命令
    usage: /villager [recruit|upgrade|help]