name: VillagePro
version: '${version}'
main: cn.popcraft.villagepro.VillagePro
api-version: 1.19
# 声明插件依赖关系
depend: [Vault]
# 可选依赖关系
softdepend: [EssentialsX, CMI]

# 插件网站
website: https://github.com/sweepikun/VillagerPro

# 自定义记分板
custom-scoreboard: true

commands:
  villagepro:
    description: Main command for VillagePro
    usage: /<command> [help]
    aliases: [vpro]
    permission: villagepro.*
    children:
      villagepro.village:
        description: Village management commands
        usage: /<command> [subcommand]
        permission: villagepro.village.*
        children:
          villagepro.village.create:
            description: Allows creating villages
            usage: /<command> create
          villagepro.village.upgrade:
            description: Allows upgrading villages
            usage: /<command> upgrade <level>
          villagepro.village.info:
            description: Allows viewing village information
            usage: /<command> info
  villager:
    description: Villager management commands
    usage: /<command> [subcommand]
    permission: villagepro.villager.*
  recruit:
    description: Recruit villagers
    usage: /<command>
    permission: villagepro.villager.recruit
  upgrade:
    description: Upgrade village capabilities
    usage: /<command> [type]
    permission: villagepro.village.upgrade
  crop:
    description: Manage crop storage
    usage: /<command> [subcommand]
    permission: villagepro.crop.*
  village:
    description: Village management commands
    usage: /<command> [subcommand]
    permission: villagepro.village.*

permissions:
  villagepro.*:
    description: Gives access to all VillagePro commands
    default: op
    children:
      villagepro.village.*: true
      villagepro.villager.*: true
      villagepro.crop.*: true
  villagepro.village.*:
    description: Gives access to all village commands
    default: op
    children:
      villagepro.village.create: true
      villagepro.village.upgrade: true
      villagepro.village.info: true
  villagepro.villager.*:
    description: Gives access to all villager commands
    default: true
    children:
      villagepro.villager.production: true
      villagepro.villager.upgrade: true
      villagepro.villager.follow: true
      villagepro.villager.info: true
      villagepro.villager.list: true
      villagepro.villager.remove: true
  villagepro.crop.*:
    description: Gives access to all crop commands
    default: true
    children:
      villagepro.crop.balance: true
      villagepro.crop.withdraw: true
      villagepro.crop.deposit: true
  villagepro.village.create:
    description: Allows creating villages
    default: true
  villagepro.village.upgrade:
    description: Allows upgrading villages
    default: true
  villagepro.village.info:
    description: Allows viewing village info
    default: true
  villagepro.villager.production:
    description: Allows opening production GUI
    default: true
  villagepro.villager.upgrade:
    description: Allows upgrading villagers
    default: true
  villagepro.villager.follow:
    description: Allows switching villager follow mode
    default: true
  villagepro.villager.info:
    description: Allows viewing villager info
    default: true
  villagepro.villager.list:
    description: Allows listing villagers
    default: true
  villagepro.villager.remove:
    description: Allows removing villagers
    default: true
  villagepro.crop.balance:
    description: Allows checking crop balance
    default: true
  villagepro.crop.withdraw:
    description: Allows withdrawing crops
    default: true
  villagepro.crop.deposit:
    description: Allows depositing crops
    default: true
  villagepro.admin:
    description: Gives access to all administrative commands
    default: op
    children:
      villagepro.*: true